spring.application.name=gateway
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
spring.cloud.config.enabled=true
server.port=8080
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/JobBoardKeycloack}

# Eureka Configuration
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Route for ROOMM service
spring.cloud.gateway.server.webmvc.routes[0].id=roomm
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://roomm
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/rooms,/api/rooms/**

# Route for EQUIPEMENT service
spring.cloud.gateway.server.webmvc.routes[1].id=equipement
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://EQUIPEMENT-MICROSERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/equipment,/api/equipment/**,/equipements,/equipements/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=RewritePath=/api/equipment(?<segment>/?.*), /equipements$\{segment}

# Route for USER service
spring.cloud.gateway.server.webmvc.routes[2].id=user-ms
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://user-ms
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/users,/api/users/**,/api/auth/**

# Route for RESERVATION service
spring.cloud.gateway.server.webmvc.routes[3].id=reservation
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://reservation
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/reservations,/api/reservations/**

# Route for EVENTS service
spring.cloud.gateway.server.webmvc.routes[4].id=events
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://events
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/events,/api/events/**

# Route for RECOMMENDATION service
spring.cloud.gateway.server.webmvc.routes[5].id=recommendation-service
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://recommendation-service
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/recommendations/**

# Route for SYSTEM MONITORING (Actuator)
spring.cloud.gateway.server.webmvc.routes[6].id=monitoring
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://user-ms
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/system/health,/api/system/info
spring.cloud.gateway.server.webmvc.routes[6].filters[0]=RewritePath=/api/system/(?<segment>.*), /actuator/${segment}

# Activer les logs de routage
logging.level.org.springframework.cloud.gateway=DEBUG
